### ISSUE TITLE
Problem with Bog Witch update

### ISSUE THREAD

**Issue by bradstowers** [AzumattDev/QueueMeMaybe#1]
Log gets bombed with this error when the mod is enabled:

```
[Error  : Unity Log] MissingMethodException: Method not found: void .Humanoid.HideHandItems()
Stack trace: (wrapper dynamic-method) Player.DMD<Player::FixedUpdate>(Player)
```

**Comment by AzumattDev** [comment]
My mods will be receiving updates over the next few days.

**Comment by bradstowers** [comment]
Awesome, just checking it in so it made it on the radar, which I'm sure is lit up like a Christmas tree with this patch.

**Comment by bradstowers** [comment]
Thanks!
